  C4Component
      title Diagrama de Componentes - PetCare Backend (NestJS)

      UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")

      Person(owner, "Dueño de mascota", "Consulta servicios, paga y agenda reservas.")
      Person(provider, "Proveedor", "Gestiona servicios y reservas.")

      Container_Boundary(petcare_system,"PetCare System"){
            Container(web, "PetCare Web", "Next.js", "Interfaz web para clientes y administración")

          Container_Boundary(backend, "PetCare Backend - NestJS") {
              Component(presentation, "Capa de Presentación", "Controllers, DTOs, Filters, JWT Guard", "Expone API REST, login y Swagger en /api-docs")
              Component(application, "Capa de Aplicación", "Use Cases, Application Services", "Orquesta casos de uso y coordina agregados")
              Component(domain, "Capa de Dominio", "Aggregates, Entities, Value Objects, Domain Services", "Contiene las reglas centrales del negocio")
              Component(infrastructure, "Capa de Infraestructura", "TypeORM Repositories, Migrations, Scrypt, Gateways", "Implementa MySQL relacional, hash de contraseñas e integraciones externas")

              Rel(presentation, application, "Invoca casos de uso")
              Rel(application, domain, "Orquesta reglas de negocio")
              Rel(application, infrastructure, "Solicita persistencia e integraciones")
              Rel_Back(domain, infrastructure, "Implementa contratos definidos por")
          }

          ContainerDb(database, "MySQL", "Aiven", "Almacena datos relacionales del sistema")
      }

      System_Ext(maps, "Google Maps Platform", "Proveedor de servicios de geolocalización")

      Rel(owner, web, "Usa", "HTTPS")
      Rel(provider, web, "Usa", "HTTPS")
      Rel(web, presentation, "Invoca endpoints", "HTTP/JSON · HTTPS")
      Rel(infrastructure, database, "Lee y escribe datos", "MySQL/TLS")
      Rel(infrastructure, maps, "Consulta API", "HTTPS/API")
